local set = vim.keymap.set

set("n", "<leader>b,", ":BufferPrevious<CR>",         {silent = true, noremap = true})
set("n", "<leader>b.", ":BufferNext<CR>",             {silent = true, noremap = true})
set("n", "<leader>b<", ":BufferMovePrevious<CR>",     {silent = true, noremap = true})
set("n", "<leader>b>", ":BufferMoveNext<CR>",         {silent = true, noremap = true})
set("n", "<leader>b1", ":BufferGoto 1<CR>",           {silent = true, noremap = true})
set("n", "<leader>b2", ":BufferGoto 2<CR>",           {silent = true, noremap = true})
set("n", "<leader>b3", ":BufferGoto 3<CR>",           {silent = true, noremap = true})
set("n", "<leader>b4", ":BufferGoto 4<CR>",           {silent = true, noremap = true})
set("n", "<leader>b5", ":BufferGoto 5<CR>",           {silent = true, noremap = true})
set("n", "<leader>b6", ":BufferGoto 6<CR>",           {silent = true, noremap = true})
set("n", "<leader>b7", ":BufferGoto 7<CR>",           {silent = true, noremap = true})
set("n", "<leader>b8", ":BufferGoto 8<CR>",           {silent = true, noremap = true})
set("n", "<leader>b9", ":BufferGoto 9<CR>",           {silent = true, noremap = true})
set("n", "<leader>bc", ":BufferClose<CR>",            {silent = true, noremap = true})
set("n", "<leader>bs", ":BufferPick<CR>",             {silent = true, noremap = true})
set("n", "<leader>bd", ":BufferOrderByDirectory<CR>", {silent = true, noremap = true})
set("n", "<leader>bl", ":BufferOrderByLanguage<CR>",  {silent = true, noremap = true})
