return {
    { '<leader>b,', ':BufferPrevious<CR>' },
    { '<leader>b.', ':BufferNext<CR>' },
    { '<leader>b<', ':BufferMovePrevious<CR>' },
    { '<leader>b>', ':BufferMoveNext<CR>' },
    { '<leader>b1', ':BufferGoto 1<CR>' },
    { '<leader>b2', ':BufferGoto 2<CR>' },
    { '<leader>b3', ':BufferGoto 3<CR>' },
    { '<leader>b4', ':BufferGoto 4<CR>' },
    { '<leader>b5', ':BufferGoto 5<CR>' },
    { '<leader>b6', ':BufferGoto 6<CR>' },
    { '<leader>b7', ':BufferGoto 7<CR>' },
    { '<leader>b8', ':BufferGoto 8<CR>' },
    { '<leader>b9', ':BufferGoto 9<CR>' },
    { '<leader>bc', ':BufferClose<CR>' },
    { '<leader>bs', ':BufferPick<CR>' },
    { '<leader>bd', ':BufferOrderByDirectory<CR>' },
    { '<leader>bl', ':BufferOrderByLanguage<CR>' },
}
