require('mappings/plugins/barbar')
-- require('mappings/plugins/lspsaga')
require('mappings/plugins/cmp')
require('mappings/plugins/nvim-tree')
require('mappings/plugins/telescope')
require('mappings/plugins/git')
require('mappings/plugins/trouble')
require('mappings/plugins/neogit')
require('mappings/plugins/dap')
require('mappings/plugins/nabla')
require('mappings/plugins/luasnip')
-- require('mappings/plugins/telekasten')
require('mappings/plugins/zk')
require('mappings/plugins/refactoring')
require('mappings/plugins/mergetool')
require('mappings/plugins/lsp_lines')
