require('plugins/packer')
require('plugins/compe')
require('plugins/telescope')
require('plugins/treesitter')
require('plugins/lspsaga')
require('plugins/lexima')
require('plugins/lsp_signature')
require('plugins/lspkind')
require('plugins/git-blame')
require('plugins/neogit')
require('plugins/latex')
require('plugins/formatter')
-- files that have nothing for now
require('plugins/nvim-tree')
