require('plugins/packer')
require('plugins/autopairs')
require('plugins/cmp')
require('plugins/telescope')
require('plugins/treesitter')
require('plugins/lspsaga')
-- require('plugins/lexima')
require('plugins/lsp_signature')
require('plugins/lspkind')
require('plugins/git-blame')
require('plugins/neogit')
require('plugins/latex')
require('plugins/formatter')
require('plugins/dap')
require('plugins/comment')
require('plugins/gps')
-- files that have nothing for now
require('plugins/nvim-tree')
